language: node_js
sudo: false

cache:
  directories:
    - node_modules

branches:
  only:
    - master
    - /^greenkeeper/.*$/

node_js:
  - "6"
before_install:
  - npm i -g npm@^3.0.0

before_script:
  - npm prune

script:
  - npm run test
  - npm run cover:check
  - npm run build
after_success:
  - npm run cover:alls
